# Generated by Django 5.2.13 on 2026-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pitcture',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='yosh',
            field=models.PositiveIntegerField(blank=True, default=15),
        ),
    ]
