# Generated by Django 5.2.13 on 2026-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
