# Generated by Django 5.2.13 on 2026-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pitcture',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
