# Generated by Django 5.2.13 on 2026-04-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_rename_pitcture_user_picture_alter_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
