# Generated by Django 5.2.13 on 2026-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yosh',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
